[metadata]
name = pynzb
version = 0.2.0
author = Eric Florenzano
author_email = floguy@gmail.com
description = pynzb is a unified API for parsing NZB files, with several concrete implementations included
long_description = file: README.rst
long_description_content_type = text/x-rst
url = http://github.com/ericflo/pynzb/tree/master
keywords = nzb,parser,xml
license = BSD
classifiers =
    Programming Language :: Python
    Topic :: Software Development :: Libraries :: Python Modules

[options]
packages = find:
include_package_data = True
zip_safe = False
install_requires =
    lxml 